# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Bot"
    groups:
      github-actions:
        patterns:
          - '*'
    cooldown:
      default-days: 7

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Bot"
    cooldown:
      default-days: 7
