[workspace]
authors = ["Chris Barker <Chris.Barker@noaa.gov>"]
channels = ["conda-forge"]
name = "cell_tree2d"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[dependencies]
numpy = ">=2.5,<3"

[feature.build.dependencies]
cython  = ">=3"
pip = "*"
python-build = "*"
cmake = "*"
scikit-build-core = ">=0.9.9"
cython-cmake = "*"
cython-lint = "*"
ninja = "*"
setuptools_scm = "*"

[feature.dev.dependencies]
ipython = "*"
ipdb = "*"
ruff = "*"

[feature.test.dependencies]
pytest = "*"
pytest-cov = "*"

[feature.py312.dependencies]
python = "~=3.12.0"

[feature.py313.dependencies]
python = "~=3.13.0"

[feature.py314.dependencies]
python = "~=3.14.0"


[environments]
default = { features = ["py312", "dev", "test", "build"], solve-group = "default" }
# using the oldest supported version for development
dev312 = ["py312", "dev", "test", "build"]
dev313 = ["py313", "dev", "test", "build"]
dev314 = ["py314", "dev", "test", "build"]
build312 = ["py312", "build"]
build313 = ["py313", "build"]
build314 = ["py314", "build"]
test312 = [ "py312", "test", "build" ]
test313 = [ "py313", "test", "build" ]
test314 = [ "py313", "test", "build" ]

[tasks]
build_wheel = {cmd = "python -m build --skip-dependency-check --no-isolation ./", default-environment = "build"}

install = { cmd = "pip install --no-deps --root-user-action=ignore --force-reinstall --no-index --only-binary=:all: --find-links=./dist/  cell_tree2d", depends-on = ["build_wheel"]}

test = { cmd = "pytest --pyargs cell_tree2d", depends-on = ["install"]}
