# Conda recipe example.
package:
    name: cell_tree2d
    version: "0.3.0"

source:
    git_url: https://github.com/NOAA-ORR-ERD/cell_tree2d
    git_tag: v0.3.0

build:
    number: 0

requirements:
  build:
    - python
    - cython
    - numpy 1.11.*

  run:
    - python
    - numpy 1.11.*

test:
  requires:
    - pytest
    - python
    - numpy

  imports:
    - cell_tree2d

  commands:
    - py.test --pyargs cell_tree2d 

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.


about:
  home: https://github.com/NOAA-ORR-ERD/cell_tree2d
  license: Public Domain
  summary: 'Data structure for rapid resolution of the "which polygon is this point in" question on unstructured grids'