all: BBTree

BBTree: testmain.o BBTree.o BoxTree.o
	c++ -g -std=c++11 -stdlib=libc++ *.o -o BBTreetest.exe

BBTree.o: BBTree.cpp
	c++ -g -std=c++11 -stdlib=libc++ -c BBTree.cpp

BoxTree.o: BoxTree.cpp
	c++ -g -std=c++11 -stdlib=libc++ -c BoxTree.cpp
testmain.o: testmain.cpp
	c++ -g -std=c++11 -stdlib=libc++ -c testmain.cpp


#stdafx.o: stdafx.cpp
#	g++ -g -std=c++11 -c stdafx.cpp
clean:
	rm *o BBTreetest.exe
