name: Run tests with miniforge
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Miniconda ${{ matrix.os }} Py${{ matrix.pyver }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: ["ubuntu-latest", "windows-latest", "macos-latest"]
            pyver: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-version: latest
          python-version: ${{ matrix.pyver }}
          conda-remove-defaults: true

      - name: Setup environment
        shell: bash -l {0}
        run: |
            conda install python=${{ matrix.pyver }} --file conda_requirements.txt

      - name: Build
        shell: bash -l {0}
        run: |
            python -m pip install --no-build-isolation -vv ./

      - name: Test
        shell: bash -l {0}
        run: |
            pytest --pyargs cell_tree2d

  lint:
    name: cython-lint linting
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-version: latest
          python-version: "3.10"
          conda-remove-defaults: true
      - name: Lint
        shell: bash -l {0}
        run: |
            conda install cython-lint
            cython-lint src
